package com.suricata.argos.WS.entidades;
// Generated 25/08/2010 08:00:38 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private Integer id;
     private Oportunidad oportunidad;
     private Tipoactividad tipoactividad;
     private Usuario usuarioByResponsableUsuario;
     private Documento documento;
     private Contacto contacto;
     private Usuario usuarioByUsuario;
     private Estado estado;
     private String titulo;
     private String descripcion;
     private Date fechaVencimiento;
     private Date fechaCreacion;
     private String descripcionCierre;
     private Set seguimientos = new HashSet(0);

    public Actividad() {
    }

	
    public Actividad(Oportunidad oportunidad, Tipoactividad tipoactividad, Usuario usuarioByUsuario, Estado estado, String titulo, Date fechaVencimiento, Date fechaCreacion) {
        this.oportunidad = oportunidad;
        this.tipoactividad = tipoactividad;
        this.usuarioByUsuario = usuarioByUsuario;
        this.estado = estado;
        this.titulo = titulo;
        this.fechaVencimiento = fechaVencimiento;
        this.fechaCreacion = fechaCreacion;
    }
    public Actividad(Oportunidad oportunidad, Tipoactividad tipoactividad, Usuario usuarioByResponsableUsuario, Documento documento, Contacto contacto, Usuario usuarioByUsuario, Estado estado, String titulo, String descripcion, Date fechaVencimiento, Date fechaCreacion, String descripcionCierre, Set seguimientos) {
       this.oportunidad = oportunidad;
       this.tipoactividad = tipoactividad;
       this.usuarioByResponsableUsuario = usuarioByResponsableUsuario;
       this.documento = documento;
       this.contacto = contacto;
       this.usuarioByUsuario = usuarioByUsuario;
       this.estado = estado;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.fechaVencimiento = fechaVencimiento;
       this.fechaCreacion = fechaCreacion;
       this.descripcionCierre = descripcionCierre;
       this.seguimientos = seguimientos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Oportunidad getOportunidad() {
        return this.oportunidad;
    }
    
    public void setOportunidad(Oportunidad oportunidad) {
        this.oportunidad = oportunidad;
    }
    public Tipoactividad getTipoactividad() {
        return this.tipoactividad;
    }
    
    public void setTipoactividad(Tipoactividad tipoactividad) {
        this.tipoactividad = tipoactividad;
    }
    public Usuario getUsuarioByResponsableUsuario() {
        return this.usuarioByResponsableUsuario;
    }
    
    public void setUsuarioByResponsableUsuario(Usuario usuarioByResponsableUsuario) {
        this.usuarioByResponsableUsuario = usuarioByResponsableUsuario;
    }
    public Documento getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(Documento documento) {
        this.documento = documento;
    }
    public Contacto getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
    }
    public Usuario getUsuarioByUsuario() {
        return this.usuarioByUsuario;
    }
    
    public void setUsuarioByUsuario(Usuario usuarioByUsuario) {
        this.usuarioByUsuario = usuarioByUsuario;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getDescripcionCierre() {
        return this.descripcionCierre;
    }
    
    public void setDescripcionCierre(String descripcionCierre) {
        this.descripcionCierre = descripcionCierre;
    }
    public Set getSeguimientos() {
        return this.seguimientos;
    }
    
    public void setSeguimientos(Set seguimientos) {
        this.seguimientos = seguimientos;
    }




}


