package com.suricata.argos.WS.entidades;
// Generated 25/08/2010 08:00:38 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private Integer id;
     private Empresa empresa;
     private String nombre;
     private String apellido;
     private String cargo;
     private String email;
     private String telefono;
     private String celular;
     private String chat;
     private String comentarios;
     private Set oportunidads = new HashSet(0);
     private Set actividads = new HashSet(0);

    public Contacto() {
    }

	
    public Contacto(Empresa empresa, String nombre, String apellido) {
        this.empresa = empresa;
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Contacto(Empresa empresa, String nombre, String apellido, String cargo, String email, String telefono, String celular, String chat, String comentarios, Set oportunidads, Set actividads) {
       this.empresa = empresa;
       this.nombre = nombre;
       this.apellido = apellido;
       this.cargo = cargo;
       this.email = email;
       this.telefono = telefono;
       this.celular = celular;
       this.chat = chat;
       this.comentarios = comentarios;
       this.oportunidads = oportunidads;
       this.actividads = actividads;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getChat() {
        return this.chat;
    }
    
    public void setChat(String chat) {
        this.chat = chat;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public Set getOportunidads() {
        return this.oportunidads;
    }
    
    public void setOportunidads(Set oportunidads) {
        this.oportunidads = oportunidads;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }




}


