package com.suricata.argos.WS.entidades;
// Generated 25/08/2010 08:00:38 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Documento generated by hbm2java
 */
public class Documento  implements java.io.Serializable {


     private Integer id;
     private Oportunidad oportunidad;
     private String nombre;
     private String ruta;
     private String tipo;
     private String tamano;
     private Set actividads = new HashSet(0);
     private Set oportunidads = new HashSet(0);

    public Documento() {
    }

	
    public Documento(String nombre, String ruta, String tipo, String tamano) {
        this.nombre = nombre;
        this.ruta = ruta;
        this.tipo = tipo;
        this.tamano = tamano;
    }
    public Documento(Oportunidad oportunidad, String nombre, String ruta, String tipo, String tamano, Set actividads, Set oportunidads) {
       this.oportunidad = oportunidad;
       this.nombre = nombre;
       this.ruta = ruta;
       this.tipo = tipo;
       this.tamano = tamano;
       this.actividads = actividads;
       this.oportunidads = oportunidads;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Oportunidad getOportunidad() {
        return this.oportunidad;
    }
    
    public void setOportunidad(Oportunidad oportunidad) {
        this.oportunidad = oportunidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getTamano() {
        return this.tamano;
    }
    
    public void setTamano(String tamano) {
        this.tamano = tamano;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }
    public Set getOportunidads() {
        return this.oportunidads;
    }
    
    public void setOportunidads(Set oportunidads) {
        this.oportunidads = oportunidads;
    }




}


