package com.suricata.argos.WS.entidades;
// Generated 25/08/2010 08:00:38 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Long rut;
     private String rubro;
     private String direccion;
     private String telefono;
     private Set oportunidads = new HashSet(0);
     private Set contactos = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String nombre) {
        this.nombre = nombre;
    }
    public Empresa(String nombre, String descripcion, Long rut, String rubro, String direccion, String telefono, Set oportunidads, Set contactos) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.rut = rut;
       this.rubro = rubro;
       this.direccion = direccion;
       this.telefono = telefono;
       this.oportunidads = oportunidads;
       this.contactos = contactos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Long getRut() {
        return this.rut;
    }
    
    public void setRut(Long rut) {
        this.rut = rut;
    }
    public String getRubro() {
        return this.rubro;
    }
    
    public void setRubro(String rubro) {
        this.rubro = rubro;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getOportunidads() {
        return this.oportunidads;
    }
    
    public void setOportunidads(Set oportunidads) {
        this.oportunidads = oportunidads;
    }
    public Set getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Set contactos) {
        this.contactos = contactos;
    }




}


