package com.suricata.argos.WS.entidades;
// Generated 25/08/2010 08:00:38 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Oportunidad generated by hbm2java
 */
public class Oportunidad  implements java.io.Serializable {


     private Integer id;
     private Contacto contacto;
     private Tipoproyecto tipoproyecto;
     private Tecnologia tecnologia;
     private Documento documento;
     private Usuario usuario;
     private Estado estado;
     private Empresa empresa;
     private String codigoInterno;
     private String titulo;
     private String descripcionCierre;
     private Date fecha;
     private Date fechaCierre;
     private Set actividads = new HashSet(0);
     private Set documentos = new HashSet(0);

    public Oportunidad() {
    }

	
    public Oportunidad(Contacto contacto, Tipoproyecto tipoproyecto, Tecnologia tecnologia, Usuario usuario, Estado estado, Empresa empresa, String titulo, Date fecha) {
        this.contacto = contacto;
        this.tipoproyecto = tipoproyecto;
        this.tecnologia = tecnologia;
        this.usuario = usuario;
        this.estado = estado;
        this.empresa = empresa;
        this.titulo = titulo;
        this.fecha = fecha;
    }
    public Oportunidad(Contacto contacto, Tipoproyecto tipoproyecto, Tecnologia tecnologia, Documento documento, Usuario usuario, Estado estado, Empresa empresa, String codigoInterno, String titulo, String descripcionCierre, Date fecha, Date fechaCierre, Set actividads, Set documentos) {
       this.contacto = contacto;
       this.tipoproyecto = tipoproyecto;
       this.tecnologia = tecnologia;
       this.documento = documento;
       this.usuario = usuario;
       this.estado = estado;
       this.empresa = empresa;
       this.codigoInterno = codigoInterno;
       this.titulo = titulo;
       this.descripcionCierre = descripcionCierre;
       this.fecha = fecha;
       this.fechaCierre = fechaCierre;
       this.actividads = actividads;
       this.documentos = documentos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Contacto getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
    }
    public Tipoproyecto getTipoproyecto() {
        return this.tipoproyecto;
    }
    
    public void setTipoproyecto(Tipoproyecto tipoproyecto) {
        this.tipoproyecto = tipoproyecto;
    }
    public Tecnologia getTecnologia() {
        return this.tecnologia;
    }
    
    public void setTecnologia(Tecnologia tecnologia) {
        this.tecnologia = tecnologia;
    }
    public Documento getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(Documento documento) {
        this.documento = documento;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getCodigoInterno() {
        return this.codigoInterno;
    }
    
    public void setCodigoInterno(String codigoInterno) {
        this.codigoInterno = codigoInterno;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcionCierre() {
        return this.descripcionCierre;
    }
    
    public void setDescripcionCierre(String descripcionCierre) {
        this.descripcionCierre = descripcionCierre;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getFechaCierre() {
        return this.fechaCierre;
    }
    
    public void setFechaCierre(Date fechaCierre) {
        this.fechaCierre = fechaCierre;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }
    public Set getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set documentos) {
        this.documentos = documentos;
    }




}


