package com.suricata.argos.WS.entidades;
// Generated 25/08/2010 08:00:38 PM by Hibernate Tools 3.2.1.GA



/**
 * Seguimientotiposeguimiento generated by hbm2java
 */
public class Seguimientotiposeguimiento  implements java.io.Serializable {


     private Integer id;
     private Tiposeguimiento tiposeguimiento;
     private Seguimiento seguimiento;

    public Seguimientotiposeguimiento() {
    }

    public Seguimientotiposeguimiento(Tiposeguimiento tiposeguimiento, Seguimiento seguimiento) {
       this.tiposeguimiento = tiposeguimiento;
       this.seguimiento = seguimiento;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tiposeguimiento getTiposeguimiento() {
        return this.tiposeguimiento;
    }
    
    public void setTiposeguimiento(Tiposeguimiento tiposeguimiento) {
        this.tiposeguimiento = tiposeguimiento;
    }
    public Seguimiento getSeguimiento() {
        return this.seguimiento;
    }
    
    public void setSeguimiento(Seguimiento seguimiento) {
        this.seguimiento = seguimiento;
    }




}


