package com.suricata.argos.WS.entidades;
// Generated 25/08/2010 08:00:38 PM by Hibernate Tools 3.2.1.GA



/**
 * Seguimientousuario generated by hbm2java
 */
public class Seguimientousuario  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private Seguimiento seguimiento;

    public Seguimientousuario() {
    }

    public Seguimientousuario(Usuario usuario, Seguimiento seguimiento) {
       this.usuario = usuario;
       this.seguimiento = seguimiento;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Seguimiento getSeguimiento() {
        return this.seguimiento;
    }
    
    public void setSeguimiento(Seguimiento seguimiento) {
        this.seguimiento = seguimiento;
    }




}


