package com.suricata.argos.WS.entidades;
// Generated 25/08/2010 08:00:38 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Seguimiento generated by hbm2java
 */
public class Seguimiento  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private Actividad actividad;
     private Date fechaVencimiento;
     private Date fechaAnuncio;
     private Integer enviado;
     private Set seguimientotiposeguimientos = new HashSet(0);
     private Set seguimientousuarios = new HashSet(0);

    public Seguimiento() {
    }

	
    public Seguimiento(Usuario usuario, Actividad actividad, Date fechaVencimiento, Date fechaAnuncio) {
        this.usuario = usuario;
        this.actividad = actividad;
        this.fechaVencimiento = fechaVencimiento;
        this.fechaAnuncio = fechaAnuncio;
    }
    public Seguimiento(Usuario usuario, Actividad actividad, Date fechaVencimiento, Date fechaAnuncio, Integer enviado, Set seguimientotiposeguimientos, Set seguimientousuarios) {
       this.usuario = usuario;
       this.actividad = actividad;
       this.fechaVencimiento = fechaVencimiento;
       this.fechaAnuncio = fechaAnuncio;
       this.enviado = enviado;
       this.seguimientotiposeguimientos = seguimientotiposeguimientos;
       this.seguimientousuarios = seguimientousuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Date getFechaAnuncio() {
        return this.fechaAnuncio;
    }
    
    public void setFechaAnuncio(Date fechaAnuncio) {
        this.fechaAnuncio = fechaAnuncio;
    }
    public Integer getEnviado() {
        return this.enviado;
    }
    
    public void setEnviado(Integer enviado) {
        this.enviado = enviado;
    }
    public Set getSeguimientotiposeguimientos() {
        return this.seguimientotiposeguimientos;
    }
    
    public void setSeguimientotiposeguimientos(Set seguimientotiposeguimientos) {
        this.seguimientotiposeguimientos = seguimientotiposeguimientos;
    }
    public Set getSeguimientousuarios() {
        return this.seguimientousuarios;
    }
    
    public void setSeguimientousuarios(Set seguimientousuarios) {
        this.seguimientousuarios = seguimientousuarios;
    }




}


