package com.suricata.argos.WS.entidades;
// Generated 25/08/2010 08:00:38 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tecnologia generated by hbm2java
 */
public class Tecnologia  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Set oportunidads = new HashSet(0);

    public Tecnologia() {
    }

	
    public Tecnologia(String nombre) {
        this.nombre = nombre;
    }
    public Tecnologia(String nombre, String descripcion, Set oportunidads) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.oportunidads = oportunidads;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getOportunidads() {
        return this.oportunidads;
    }
    
    public void setOportunidads(Set oportunidads) {
        this.oportunidads = oportunidads;
    }




}


