package com.suricata.argos.WS.entidades;
// Generated 25/08/2010 08:00:38 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoactividad generated by hbm2java
 */
public class Tipoactividad  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Set actividads = new HashSet(0);

    public Tipoactividad() {
    }

	
    public Tipoactividad(String nombre) {
        this.nombre = nombre;
    }
    public Tipoactividad(String nombre, String descripcion, Set actividads) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.actividads = actividads;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }




}


