package com.suricata.argos.WS.entidades;
// Generated 25/08/2010 08:00:38 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tiposeguimiento generated by hbm2java
 */
public class Tiposeguimiento  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Set seguimientotiposeguimientos = new HashSet(0);

    public Tiposeguimiento() {
    }

	
    public Tiposeguimiento(String nombre) {
        this.nombre = nombre;
    }
    public Tiposeguimiento(String nombre, String descripcion, Set seguimientotiposeguimientos) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.seguimientotiposeguimientos = seguimientotiposeguimientos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSeguimientotiposeguimientos() {
        return this.seguimientotiposeguimientos;
    }
    
    public void setSeguimientotiposeguimientos(Set seguimientotiposeguimientos) {
        this.seguimientotiposeguimientos = seguimientotiposeguimientos;
    }




}


