package com.suricata.argos.WS.entidades;
// Generated 25/08/2010 08:00:38 PM by Hibernate Tools 3.2.1.GA



/**
 * Usuariorol generated by hbm2java
 */
public class Usuariorol  implements java.io.Serializable {


     private Integer id;
     private Rol rol;
     private Usuario usuario;

    public Usuariorol() {
    }

    public Usuariorol(Rol rol, Usuario usuario) {
       this.rol = rol;
       this.usuario = usuario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


