package com.suricata.argos.WS.vo;
// Generated 18/08/2010 05:19:33 PM by Hibernate Tools 3.2.1.GA

import com.suricata.argos.WS.entidades.*;




/**
 * Seguimientotiposeguimiento generated by hbm2java
 */
public class SeguimientoTipoSeguimientoVo  implements java.io.Serializable {


     private int id;
     private TipoSeguimientoVo tiposeguimiento;
     private SeguimientoVo seguimiento;

    public SeguimientoTipoSeguimientoVo() {
    }

    public SeguimientoTipoSeguimientoVo(int id, TipoSeguimientoVo tiposeguimiento, SeguimientoVo seguimiento) {
       this.id = id;
       this.tiposeguimiento = tiposeguimiento;
       this.seguimiento = seguimiento;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TipoSeguimientoVo getTiposeguimiento() {
        return this.tiposeguimiento;
    }
    
    public void setTiposeguimiento(TipoSeguimientoVo tiposeguimiento) {
        this.tiposeguimiento = tiposeguimiento;
    }
    public SeguimientoVo getSeguimiento() {
        return this.seguimiento;
    }
    
    public void setSeguimiento(SeguimientoVo seguimiento) {
        this.seguimiento = seguimiento;
    }




}


